CREATE SCHEMA IF NOT EXISTS silver;
DROP TABLE IF EXISTS silver.microsoft_security_incident;    
CREATE TABLE silver.microsoft_security_incident (
    -- Identificadores
    id BIGINT PRIMARY KEY,
    org_id INT NOT NULL,
    incident_id INT NOT NULL,
    alert_id INT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    year INT GENERATED ALWAYS AS (EXTRACT(YEAR FROM timestamp)::INT) STORED,
    month INT GENERATED ALWAYS AS (EXTRACT(MONTH FROM timestamp)::INT) STORED,
    day INT GENERATED ALWAYS AS (EXTRACT(DAY FROM timestamp)::INT) STORED,
    hour INT GENERATED ALWAYS AS (EXTRACT(HOUR FROM timestamp)::INT) STORED,
    day_of_week INT GENERATED ALWAYS AS (EXTRACT(DOW FROM timestamp)::INT) STORED,
    detector_id INT NOT NULL,
    alert_title INT NOT NULL,
    category INT NOT NULL,
    mitre_techniques INT NOT NULL,
    incident_grade INT NOT NULL,
    entity_type INT NOT NULL,
    evidence_role INT NOT NULL,
    device_id BIGINT,
    sha256 BIGINT,
    ip_address BIGINT,
    CREATE SCHEMA IF NOT EXISTS silver;
    DROP TABLE IF EXISTS silver.microsoft_security_incident;
    CREATE TABLE silver.microsoft_security_incident (
        -- Identificadores e metadados
        id BIGINT PRIMARY KEY,
        org_id INT,
        incident_id INT,
        alert_id INT,
        -- timestamp original da fonte: pode ser numérico ou ISO; manter TEXT para tolerância
        timestamp TEXT,
        -- campos descritivos/textuais
        detector_id INT,
        alert_title VARCHAR(1000),
        category VARCHAR(255),
        mitre_techniques TEXT,
        incident_grade VARCHAR(50),
        entity_type VARCHAR(255),
        evidence_role VARCHAR(255),
        device_id BIGINT,
        sha256 VARCHAR(128),
        ip_address VARCHAR(50),
        url TEXT,
        account_sid VARCHAR(255),
        account_upn VARCHAR(255),
        account_object_id VARCHAR(255),
        account_name VARCHAR(255),
        device_name VARCHAR(255),
        network_message_id VARCHAR(255),
        email_cluster_id VARCHAR(255),
        registry_key VARCHAR(1000),
        registry_value_name VARCHAR(255),
        registry_value_data TEXT,
        application_id VARCHAR(255),
        application_name VARCHAR(255),
        oauth_application_id VARCHAR(255),
        threat_family VARCHAR(255),
        file_name VARCHAR(255),
        folder_path TEXT,
        resource_id_name VARCHAR(255),
        resource_type VARCHAR(255),
        roles VARCHAR(255),
        os_family VARCHAR(255),
        os_version VARCHAR(255),
        antispam_direction VARCHAR(255),
        suspicion_level VARCHAR(50),
        last_verdict VARCHAR(255),
        country_code VARCHAR(10),
        state VARCHAR(255),
        city VARCHAR(255)
    );
